### ISSUE TITLE
[Feature Request] Allow `voice` string instead of base64 wav

### ISSUE THREAD

**Issue by kwaa** [astramind-ai/Auralis#24]
Nice project! I wish it were a little easier to use though.

The current API server requires WAV file to be converted to base64 as a `voice` parameter,
which makes it less suitable for use in a browser.

As an alternative, it might be possible to read a sample folder when `voice` is a string to find the corresponding WAV file:

> `female => $PWD/samples/female.wav`

```bash
curl http://localhost:8000/v1/audio/speech \
  -H "Content-Type: application/json" \
  -d '{
    "model": "xttsv2",
    "input": "The quick brown fox jumped over the lazy dog.",
    "voice": "female",
    "response_format": "wav"
  }' \
  --output speech.wav
```

It is also still possible to receive an existing base64 wav, just make sure it is an array.

**Comment by mlinmg** [comment]
You can already refer to local paths for the voice referenc, you could do 
curl http://localhost:8000/v1/audio/speech \
  -H "Content-Type: application/json" \
  -d '{
    "model": "xttsv2",
    "input": "The quick brown fox jumped over the lazy dog.",
    "voice": "some/path/on/the/server/female.wav",
    "response_format": "wav"
  }' \
  --output speech.wav

**Comment by maxi1134** [comment]
> You can already refer to local paths for the voice referenc, you could do curl http://localhost:8000/v1/audio/speech -H "Content-Type: application/json" -d '{ "model": "xttsv2", "input": "The quick brown fox jumped over the lazy dog.", "voice": "some/path/on/the/server/female.wav", "response_format": "wav" }' --output speech.wav

I'm trying the following:

```
curl -X 'POST' \
  'http://192.168.0.14:8001/v1/audio/speech' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "input": "this is a test",
  "model": "xttsv2",
  "voice": ["/app/examples/ncage.wav"],
  "response_format": "wav"
}'
```

With no luck, it returns:
```

{
  "detail": [
    {
      "type": "value_error",
      "loc": [
        "body",
        "voice"
      ],
      "msg": "Value error, Invalid base64 encoding in voice file",
      "input": [
        "/app/examples/ncage.wav"
      ],
      "ctx": {
        "error": {}
      }
    }
  ]
}

```
I've properly mounted the volumes in my docker

```
services:
  auralis:
    container_name: auralis
    build:
      context: .
      tags:
        - auralis:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - /home/maxi1134/docker-compose/Auralis:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: --host 0.0.0.0 --port 8001 --model AstraMindAI/xttsv2 --gpt_model AstraMindAI/xtts2-gpt --max_concurrency 8 --vllm_logging_level warn

```

And can see the files while doing 

`sudo docker exec -it auralis  /bin/bash`
